-- ====================================================================
-- Cargar SOLO las 85 propiedades de Querétaro (inventario Junio 2026)
-- Grupo Inmobiliario Orquídeas — ejecutar en Supabase > SQL Editor
-- ====================================================================

-- 1) Columna para enlazar fotos por clave (idempotente)
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS clave_control text;

-- 2) Permitir tipos adicionales (Local, Bodega) ademas de los originales
ALTER TABLE public.properties DROP CONSTRAINT IF EXISTS properties_tipo_check;
ALTER TABLE public.properties
  ADD CONSTRAINT properties_tipo_check
  CHECK (tipo IN ('Casa','Departamento','Terreno','Local','Bodega'));

-- 3) Dejar SOLO estas propiedades (borra el catalogo actual de ejemplo)
DELETE FROM public.properties;

-- 4) Insertar las 85 de Queretaro (precio = valor de referencia)
INSERT INTO public.properties
  (clave_control, titulo, tipo, operacion, precio, ubicacion, descripcion, recamaras, banos, area, imagenes, destacada, activa, contacto_nombre, contacto_telefono, contacto_email)
VALUES
  ('09701', 'Casa en San Pedrito Peñuelas, Querétaro', 'Casa', 'Venta', 759200.0, 'San Pedrito Peñuelas, Querétaro, Querétaro', 'Casa habitación de 1 nivel con P.B.- sala, comedor, cocina, 1 baño y una alcoba (pie de casa). Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 41.22 m². Con Escritura. Posesión física: No. Clave de control: 09701.', NULL, 1, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('13436', 'Casa en San Pedrito Peñuelas, Querétaro', 'Casa', 'Venta', 748500.0, 'San Pedrito Peñuelas, Querétaro, Querétaro', 'Casa habitación unifamiliar, 1 nivel Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 40 m². Con Escritura. Posesión física: No. Clave de control: 13436.', NULL, NULL, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('13979', 'Casa en San Pedrito Peñuelas, Querétaro', 'Casa', 'Venta', 748500.0, 'San Pedrito Peñuelas, Querétaro, Querétaro', 'Casa habitación de una sola planta. consta de: sala, comedor, cocina, 1 baño, una alcoba y patio de servicio. Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 40 m². Con Escritura. Posesión física: No. Clave de control: 13979.', NULL, 1, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('15721', 'Casa en Des. Hab. San Pedrito Peñuelas, Querétaro', 'Casa', 'Venta', 748500.0, 'Des. Hab. San Pedrito Peñuelas, Querétaro, Querétaro', 'Casa habitación de 1 nivel con sala comedor, cocina, 1 recámara, 1 baño y patio de servicio. Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 40 m². Con Escritura. Posesión física: No. Clave de control: 15721.', 1, 1, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('16009', 'Casa en Fracc. Ex Hacienda Santa Ana, Querétaro', 'Casa', 'Venta', 503000.0, 'Fracc. Ex Hacienda Santa Ana, Querétaro, Querétaro', 'Casa habitación de 1 nivel con cochera descubierta para 1 automóvil compacto, sala-comedor-cocina, recámara con espacio para clóset, baño completo, patio de servicio y jardín. Tipo: Vivienda (Casa). Superficie de terreno: 91.37 m². Construcción: 52.22 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 16009.', NULL, NULL, 91.37, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('17821', 'Departamento en Fracc. El Jacal, Querétaro', 'Departamento', 'Venta', 1290200.0, 'Fracc. El Jacal, Querétaro, Querétaro', 'Departamento de 1 nivel con un cajón de estacionamiento. Tipo: Vivienda (Departamento). Superficie de terreno: 63 m². Construcción: 90 m². Con Escritura. Posesión física: No. Clave de control: 17821.', NULL, NULL, 63.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('17890', 'Terreno agostadero en Vizarron, Cadereyta de Montes', 'Terreno', 'Venta', 857300.0, 'Vizarron, Cadereyta de Montes, Querétaro', 'Predio rústico irregular de romerío a terreno montuoso Tipo: Terreno Rústico (Agostadero). Superficie de terreno: 30021.64 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 17890.', NULL, NULL, 30021.64, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('18574', 'Casa en San Antonio del Maurel, Querétaro', 'Casa', 'Venta', 564000.0, 'San Antonio del Maurel, Querétaro, Querétaro', 'Casa habitación de 2 niveles con P.B.- sala, comedor, cocina, cubo de escalera, patio de servicio y P.A.- 1 recámara, alcoba, tapanco. Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 47 m². Con Escritura. Posesión física: No. Clave de control: 18574.', 1, NULL, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('19957', 'Casa en Población Villa Corregidora, Querétaro', 'Casa', 'Venta', 6312600.0, 'Población Villa Corregidora, Querétaro, Querétaro', 'Casa habitación, 1 nivel Tipo: Vivienda (Casa). Superficie de terreno: 2357 m². Construcción: 320 m². Con Escritura. Posesión física: No. Clave de control: 19957.', NULL, NULL, 2357.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('20197', 'Terreno habitacional en Texas, Querétaro', 'Terreno', 'Venta', 1128900.0, 'Texas, Querétaro, Querétaro', 'Lote de terreno urbano habitacional Tipo: Terreno Urbano (Habitacional). Superficie de terreno: 300 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 20197.', NULL, NULL, 300.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('34164', 'Casa en Fracc. Lomalinda, San Juan Del Río', 'Casa', 'Venta', 2517000.0, 'Fracc. Lomalinda, San Juan Del Río, Querétaro', 'Casa habitación, 1 nivel Tipo: Vivienda (Casa). Superficie de terreno: 1600 m². Construcción: 248 m². Con Escritura. Posesión física: No. Clave de control: 34164.', NULL, NULL, 1600.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('35880', 'Casa en San Antonio del Maurel, Querétaro', 'Casa', 'Venta', 612000.0, 'San Antonio del Maurel, Querétaro, Querétaro', 'Casa habitación de 2 niveles con sala, comedor, medio baño, cocina, antecomedor, patio de servicio, vestíbulo, baño completo y recámara principal con balcón. Tipo: Vivienda (Casa). Superficie de terreno: 35.74 m². Construcción: 57.48 m². Con Escritura. Posesión física: No. Clave de control: 35880.', NULL, NULL, 35.74, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('35999', 'Casa en Barrio de Los Vazquez, Cadereyta de Montes', 'Casa', 'Venta', 1486000.0, 'Barrio de Los Vazquez, Cadereyta de Montes, Querétaro', 'Garage, salon, acceso a casa, sala-comedor, cocina, patio de servicio, cubo escalera, baño completo y 2 recamaras; planta alta en proceso de construcción. Tipo: Vivienda (Casa). Superficie de terreno: 286 m². Construcción: 208.13 m². Con Escritura. Posesión física: No. Clave de control: 35999.', 2, NULL, 286.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('37218', 'Casa en Emiliano Zapata, Corregidora', 'Casa', 'Venta', 1412000.0, 'Emiliano Zapata, Corregidora, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 688.5 m². Construcción: 351 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 37218.', NULL, NULL, 688.5, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('38436', 'Casa en Exhacienda de la Capilla, Querétaro', 'Casa', 'Venta', 927000.0, 'Exhacienda de la Capilla, Querétaro, Querétaro', 'Casa habitación de 2 niveles, consta de sala, comedor, 2 recámaras, baño completo, patio de servicio y un cajón de estacionamiento. Tipo: Vivienda (Casa). Superficie de terreno: 91.12 m². Construcción: 93.95 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 38436.', 2, NULL, 91.12, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('39148', 'Casa en Fracc. Misión Mariana III, Corregidora', 'Casa', 'Venta', 1428000.0, 'Fracc. Misión Mariana III, Corregidora, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 83.44 m². Con Escritura. Posesión física: No. Clave de control: 39148.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('42378', 'Casa en Fracc. Parque Santiago, Querétaro', 'Casa', 'Venta', 622000.0, 'Fracc. Parque Santiago, Querétaro, Querétaro', 'Casa habitación, 1 nivel Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 60.6 m². Con Escritura. Posesión física: No. Clave de control: 42378.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('42485', 'Casa en Fracc. Loma IX, Querétaro', 'Casa', 'Venta', 574000.0, 'Fracc. Loma IX, Querétaro, Querétaro', 'Casa habitación, 1 nivel Tipo: Vivienda (Casa). Superficie de terreno: 69.52 m². Construcción: 47.82 m². Con Escritura. Posesión física: No. Clave de control: 42485.', NULL, NULL, 69.52, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('43546', 'Casa en Fraccionamiento Santuarios del Cerrito, Corregidora', 'Casa', 'Venta', 1465000.0, 'Fraccionamiento Santuarios del Cerrito, Corregidora, Querétaro', 'Casa habitación, 1 nivel Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 107.36 m². Con Escritura. Posesión física: No. Clave de control: 43546.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('44236', 'Casa en Villas Campestre, Corregidora', 'Casa', 'Venta', 1662900.0, 'Villas Campestre, Corregidora, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 105 m². Construcción: 132 m². Con Escritura. Posesión física: No. Clave de control: 44236.', NULL, NULL, 105.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('44414', 'Casa en Fracc. Ciudad Satelite, Querétaro', 'Casa', 'Venta', 1111200.0, 'Fracc. Ciudad Satelite, Querétaro, Querétaro', 'Casa habitación en condominio Tipo: Vivienda (Casa). Superficie de terreno: 163.13 m². Construcción: 76.4 m². Con Escritura. Posesión física: No. Clave de control: 44414.', NULL, NULL, 163.13, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('46698', 'Casa en Fracc. Ex Hacienda Santana, Querétaro', 'Casa', 'Venta', 542000.0, 'Fracc. Ex Hacienda Santana, Querétaro, Querétaro', 'Casa habitación, 1 nivel Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 52.22 m². Con Escritura. Posesión física: No. Clave de control: 46698.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('47432', 'Casa en Fraccionamiento Las Teresas, Querétaro', 'Casa', 'Venta', 1371000.0, 'Fraccionamiento Las Teresas, Querétaro, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 162.08 m². Construcción: 142.71 m². Con Escritura. Posesión física: No. Clave de control: 47432.', NULL, NULL, 162.08, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('48064', 'Casa en Fracc. San Pedrito Peñuelas, Querétaro', 'Casa', 'Venta', 748200.0, 'Fracc. San Pedrito Peñuelas, Querétaro, Querétaro', 'Casa en condominio de 1 nivel: sala, comedor, cocina, patio de servicio, 1 baño completo, 1 recámara y un cajón de estacionamiento al frente. Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 39.97 m². Con Escritura. Posesión física: No. Clave de control: 48064.', 1, 1, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('50907', 'Casa en Ferrocarriles Secc Rinconada Sta Anita, Querétaro', 'Casa', 'Venta', 1340000.0, 'Ferrocarriles Secc Rinconada Sta Anita, Querétaro, Querétaro', 'Casa habitación de 2 niveles con cochera para 2 autos, medio baño, sala comedor, cocina, patio de servicio y recámaras en planta alta. Tipo: Vivienda (Casa). Superficie de terreno: 108.05 m². Construcción: 89.65 m². Con Escritura. Posesión física: No. Clave de control: 50907.', NULL, NULL, 108.05, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('51824', 'Casa en Loma Bonita, Querétaro', 'Casa', 'Venta', 1843800.0, 'Loma Bonita, Querétaro, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 0 m². Construcción: 0 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 51824.', NULL, NULL, 0.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('52166', 'Casa en Parque Santiago Etapa 3, Querétaro', 'Casa', 'Venta', 1425000.0, 'Parque Santiago Etapa 3, Querétaro, Querétaro', 'Casa habitación de 1 nivel, consta de sala comedor, cocina, 2 recámaras y 1 baño. Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 81.34 m². Con Escritura. Posesión física: No. Clave de control: 52166.', 2, 1, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('53661', 'Casa en San Pablo IV Etapa, Querétaro', 'Casa', 'Venta', 763100.0, 'San Pablo IV Etapa, Querétaro, Querétaro', 'Casa habitación que consta de 2 niveles, 3 recámaras y 1.5 baños Tipo: Vivienda (Casa). Superficie de terreno: 44.7 m². Construcción: 70.7 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 53661.', 3, 5, 44.7, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('53669', 'Casa en Rancho Bellavista, Querétaro', 'Casa', 'Venta', 805000.0, 'Rancho Bellavista, Querétaro, Querétaro', 'Casa en condominio, 2 niveles, 3 recamaras, 1.5 baños Tipo: Vivienda (Casa). Superficie de terreno: 86.2 m². Construcción: 67.59 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 53669.', 3, 5, 86.2, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('54080', 'Casa en Milenio III, Querétaro', 'Casa', 'Venta', 3334000.0, 'Milenio III, Querétaro, Querétaro', 'Casa habitación de 2 niveles: PB vestíbulo, sala, comedor, cocina, sanitario; PA 3 recámaras, 2 baños; jardín y estacionamiento. Tipo: Vivienda (Casa). Superficie de terreno: 226.92 m². Construcción: 245.12 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 54080.', 3, 2, 226.92, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('54319', 'Casa en Fracc. Residencial Tejeda, Corregidora', 'Casa', 'Venta', 8254100.0, 'Fracc. Residencial Tejeda, Corregidora, Querétaro', 'Casa habitación de varios niveles con sótano (cochera, salón de juegos, medio baño), planta baja (cochera, sala, comedor, cocina, terraza) y recámaras en pisos superiores. Tipo: Vivienda (Casa). Superficie de terreno: 250 m². Construcción: 522.9 m². Con Escritura. Posesión física: No. Clave de control: 54319.', NULL, NULL, 250.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('55478', 'Local oficinas en Medievo XXI, Querétaro', 'Local', 'Venta', 945000.0, 'Medievo XXI, Querétaro, Querétaro', 'Oficina Tipo: Locales (Oficinas). Superficie de terreno: 66 m². Construcción: 64 m². Con Escritura. Posesión física: No. Clave de control: 55478.', NULL, NULL, 66.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('55652', 'Casa en Fracc. San Miguel, Segunda Etapa, Querétaro', 'Casa', 'Venta', 1094000.0, 'Fracc. San Miguel, Segunda Etapa, Querétaro, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 108.62 m². Construcción: 111.64 m². Con Escritura. Posesión física: No. Clave de control: 55652.', NULL, NULL, 108.62, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('55962', 'Casa en Fracc. Misión de San José, Corregidora', 'Casa', 'Venta', 761900.0, 'Fracc. Misión de San José, Corregidora, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 67.5 m². Construcción: 51.25 m². Con Escritura. Posesión física: No. Clave de control: 55962.', NULL, NULL, 67.5, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('57016', 'Casa en Soriano, Colón', 'Casa', 'Venta', 1778200.0, 'Soriano, Colón, Querétaro', 'Casa habitación que consta de cochera, sala, comedor, cocina, recámaras, baño completo y patio de servicio. Tipo: Vivienda (Casa). Superficie de terreno: 1313 m². Construcción: 117.48 m². Con Escritura. Posesión física: No. Clave de control: 57016.', NULL, NULL, 1313.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('57017', 'Bodega en Barrio de Tepetate, Colón', 'Bodega', 'Venta', 4222600.0, 'Barrio de Tepetate, Colón, Querétaro', 'Bodega con área de maniobras Tipo: Bodega/Nave (Almacen). Superficie de terreno: 5976 m². Construcción: 38 m². Con Escritura. Posesión física: No. Clave de control: 57017.', NULL, NULL, 5976.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('57018', 'Bodega en Barrio de Colon, Colón', 'Bodega', 'Venta', 990200.0, 'Barrio de Colon, Colón, Querétaro', 'Inmueble que consta de bodega y área de maniobras. Tipo: Bodega/Nave (Almacen). Superficie de terreno: 277 m². Construcción: 199 m². Con Escritura. Posesión física: No. Clave de control: 57018.', NULL, NULL, 277.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('57019', 'Casa en Soriano, Colón', 'Casa', 'Venta', 2299300.0, 'Soriano, Colón, Querétaro', 'Casa habitación que consta de cochera, sala, comedor, cocina, recámaras, baño completo y patio de servicio. Tipo: Vivienda (Casa). Superficie de terreno: 950 m². Construcción: 515 m². Con Escritura. Posesión física: No. Clave de control: 57019.', NULL, NULL, 950.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('57283', 'Bodega en Santa Catarina, Querétaro', 'Bodega', 'Venta', 2146000.0, 'Santa Catarina, Querétaro, Querétaro', 'Terreno con 2 oficinas: planta baja con cochera, cobertizo, medio baño, bodega y oficina; planta sótano con pórtico y oficina. Tipo: Bodega/Nave (Almacen). Superficie de terreno: 532 m². Construcción: 209.15 m². Con Escritura. Posesión física: No. Clave de control: 57283.', NULL, NULL, 532.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('58133', 'Casa en Loma VIII, Querétaro', 'Casa', 'Venta', 670200.0, 'Loma VIII, Querétaro, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 101.68 m². Construcción: 60.39 m². Con Escritura. Posesión física: No. Clave de control: 58133.', NULL, NULL, 101.68, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('59931', 'Casa en México, San Juan Del Río', 'Casa', 'Venta', 1570000.0, 'México, San Juan Del Río, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 200 m². Construcción: 122.93 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 59931.', NULL, NULL, 200.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('60246', 'Casa en San Miguel 2a etapa, Querétaro', 'Casa', 'Venta', 1429000.0, 'San Miguel 2a etapa, Querétaro, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 88.87 m². Con Escritura. Posesión física: Si. Clave de control: 60246.', NULL, NULL, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('60410', 'Terreno agostadero en Lagunita de San Diego, Landa de Matamoros', 'Terreno', 'Venta', 1333000.0, 'Lagunita de San Diego, Landa de Matamoros, Querétaro', 'Agostadero natural para ganadería de libre pastoreo, agrícola de riego y temporal. Tipo: Terreno Rústico (Agostadero). Superficie de terreno: 400000 m². Construcción: 0 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 60410.', NULL, NULL, 400000.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('60474', 'Terreno habitacional en Desarrollo Centro Sur, Querétaro', 'Terreno', 'Venta', 44057000.0, 'Desarrollo Centro Sur, Querétaro, Querétaro', 'Terreno en breña urbano sin construcciones Tipo: Terreno Urbano (Habitacional). Superficie de terreno: 4230.1 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 60474.', NULL, NULL, 4230.1, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('60752', 'Casa en La Uca, Ezequiel Montes', 'Casa', 'Venta', 2329000.0, 'La Uca, Ezequiel Montes, Querétaro', 'Casa habitación de 2 niveles: estancia, comedor, cocina, baños y 3 recámaras. Tipo: Vivienda (Casa). Superficie de terreno: 287 m². Construcción: 222.2 m². Con Escritura. Posesión física: Si. Clave de control: 60752.', 3, NULL, 287.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('60844', 'Casa en Los Heroes Queretaro, El Marqués', 'Casa', 'Venta', 627800.0, 'Los Heroes Queretaro, El Marqués, Querétaro', 'Casa habitación 1 nivel con cajón de estacionamiento Tipo: Vivienda (Casa). Superficie de terreno: 54 m². Construcción: 33.75 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 60844.', NULL, NULL, 54.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('61108', 'Casa en Condominio Medievo XXl, Querétaro', 'Casa', 'Venta', 732000.0, 'Condominio Medievo XXl, Querétaro, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 63.99 m². Construcción: 51 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 61108.', NULL, NULL, 63.99, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('61803', 'Terreno habitacional en Hacienda las Nueces, San Juan Del Río', 'Terreno', 'Venta', 547400.0, 'Hacienda las Nueces, San Juan Del Río, Querétaro', 'Lote baldío Tipo: Terreno Urbano (Habitacional). Superficie de terreno: 97.5 m². Construcción: 0 m². Con Escritura. Posesión física: No. Clave de control: 61803.', NULL, NULL, 97.5, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('61984', 'Casa en Cerrada de Santa Anita, Corregidora', 'Casa', 'Venta', 2396000.0, 'Cerrada de Santa Anita, Corregidora, Querétaro', 'Casa habitación de dos niveles: PB medio baño, estancia, comedor, cocina, área de lavado, cuarto de servicio con baño; PA recámara con sala de estar, closet y baño, y recámaras. Tipo: Vivienda (Casa). Superficie de terreno: 116.36 m². Construcción: 135.05 m². Con Escritura. Posesión física: Si. Clave de control: 61984.', NULL, NULL, 116.36, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('62195', 'Casa en San Miguel, Segunda Etapa, Querétaro', 'Casa', 'Venta', 1321000.0, 'San Miguel, Segunda Etapa, Querétaro, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 96 m². Construcción: 69.5 m². Con Escritura. Posesión física: No. Clave de control: 62195.', NULL, NULL, 96.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('62321', 'Casa en Fracc San Miguel, Querétaro', 'Casa', 'Venta', 580000.0, 'Fracc San Miguel, Querétaro, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 63.94 m². Con Escritura. Posesión física: No. Clave de control: 62321.', NULL, NULL, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63089', 'Casa en Rincones del Marques, El Marqués', 'Casa', 'Venta', 1542300.0, 'Rincones del Marques, El Marqués, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 93.3 m². Construcción: 84.28 m². Con Escritura. Posesión física: No. Clave de control: 63089.', NULL, NULL, 93.3, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63240', 'Casa en Ejido San Miguel Carrillo, Querétaro', 'Casa', 'Venta', 987000.0, 'Ejido San Miguel Carrillo, Querétaro, Querétaro', 'Casa habitación de un nivel: sala, comedor, cocina, patio de servicio, 2 recámaras, 1 baño completo y cajón de estacionamiento. Tipo: Vivienda (Casa). Superficie de terreno: 60.75 m². Construcción: 47.43 m². Con Escritura. Posesión física: Si. Clave de control: 63240.', 2, 1, 60.75, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63242', 'Casa en Bosques del Acueducto, Querétaro', 'Casa', 'Venta', 6957000.0, 'Bosques del Acueducto, Querétaro, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 232.1 m². Construcción: 362.36 m². Con Escritura. Posesión física: Si. Clave de control: 63242.', NULL, NULL, 232.1, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63684', 'Casa en Pueblito Colonial, Corregidora', 'Casa', 'Venta', 1950000.0, 'Pueblito Colonial, Corregidora, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 119 m². Construcción: 132.65 m². Con Escritura. Posesión física: Si. Clave de control: 63684.', NULL, NULL, 119.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63750', 'Casa en Loma Bonita, Carrillo Puerto', 'Casa', 'Venta', 1950000.0, 'Loma Bonita, Carrillo Puerto, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 361.11 m². Construcción: 145.51 m². Con Escritura. Posesión física: No. Clave de control: 63750.', NULL, NULL, 361.11, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63894', 'Casa en San Mateo, Corregidora', 'Casa', 'Venta', 2272000.0, 'San Mateo, Corregidora, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 147.49 m². Construcción: 166.4 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 63894.', NULL, NULL, 147.49, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('64089', 'Casa en El Mirador, El Marqués', 'Casa', 'Venta', 1703000.0, 'El Mirador, El Marqués, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 169.99 m². Construcción: 122.84 m². Con Escritura. Posesión física: No. Clave de control: 64089.', NULL, NULL, 169.99, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('64262', 'Terreno agrícola en Ex hacienda de Jofre, Querétaro', 'Terreno', 'Venta', 2666900.0, 'Ex hacienda de Jofre, Querétaro, Querétaro', 'Terreno en breña Tipo: Terreno Rústico (Agrícola). Superficie de terreno: 1121 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 64262.', NULL, NULL, 1121.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('64436', 'Casa en Fracc. Villas del Mesón, Querétaro', 'Casa', 'Venta', 11669000.0, 'Fracc. Villas del Mesón, Querétaro, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 1207 m². Construcción: 547.04 m². Con Escritura. Posesión física: Si. Clave de control: 64436.', NULL, NULL, 1207.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('64533', 'Casa en Fracc. Cuesta Bonita, Querétaro', 'Casa', 'Venta', 1618000.0, 'Fracc. Cuesta Bonita, Querétaro, Querétaro', 'Casa habitación en condominio, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 112.26 m². Construcción: 139 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 64533.', NULL, NULL, 112.26, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('65038', 'Casa en Los Candiles, Corregidora', 'Casa', 'Venta', 2055000.0, 'Los Candiles, Corregidora, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 105 m². Construcción: 136.96 m². Con Escritura. Posesión física: Si. Clave de control: 65038.', NULL, NULL, 105.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('65259', 'Casa en Residencial Balvanera, Corregidora', 'Casa', 'Venta', 11990000.0, 'Residencial Balvanera, Corregidora, Querétaro', 'Casa habitación en fraccionamiento privado Tipo: Vivienda (Casa). Superficie de terreno: 1137.19 m². Construcción: 668.71 m². Con Escritura. Posesión física: Si. Clave de control: 65259.', NULL, NULL, 1137.19, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('65435', 'Terreno campestre en Ex hacienda de Jofre, Querétaro', 'Terreno', 'Venta', 2747700.0, 'Ex hacienda de Jofre, Querétaro, Querétaro', 'Terreno en breña Tipo: Terreno Rústico (Campestre). Superficie de terreno: 1155 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 65435.', NULL, NULL, 1155.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66362', 'Casa en Los Sauces, Querétaro', 'Casa', 'Venta', 1452000.0, 'Los Sauces, Querétaro, Querétaro', 'Casa habitación con local comercial Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 130.84 m². Con Escritura. Posesión física: Si. Clave de control: 66362.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66424', 'Casa en Hacienda del Bosque, Corregidora', 'Casa', 'Venta', 1463000.0, 'Hacienda del Bosque, Corregidora, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 97.33 m². Construcción: 79.75 m². Con Escritura. Posesión física: Si. Clave de control: 66424.', NULL, NULL, 97.33, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66443', 'Casa en Jardines del Valle, San Juan Del Río', 'Casa', 'Venta', 2630000.0, 'Jardines del Valle, San Juan Del Río, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 161 m². Construcción: 230.87 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 66443.', NULL, NULL, 161.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66485', 'Casa en Los Héroes, El Marqués', 'Casa', 'Venta', 579000.0, 'Los Héroes, El Marqués, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 54 m². Construcción: 42.26 m². Con Escritura. Posesión física: No. Clave de control: 66485.', NULL, NULL, 54.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66716', 'Casa en La Guitarrilla, San Juan Del Río', 'Casa', 'Venta', 2074000.0, 'La Guitarrilla, San Juan Del Río, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 119 m². Construcción: 115.88 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 66716.', NULL, NULL, 119.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66936', 'Casa en Pirámides, Corregidora', 'Casa', 'Venta', 1580097.03, 'Pirámides, Corregidora, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 120 m². Construcción: 0 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 66936.', NULL, NULL, 120.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('67008', 'Casa en Barrio de San Isidro, San Juan Del Río', 'Casa', 'Venta', 1946000.0, 'Barrio de San Isidro, San Juan Del Río, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 223 m². Construcción: 134.97 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 67008.', NULL, NULL, 223.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('67390', 'Departamento en Real de la Loma, Querétaro', 'Departamento', 'Venta', 729000.0, 'Real de la Loma, Querétaro, Querétaro', 'Departamento habitacional en nivel tres: cocina, estancia, dos recamaras, baño completo, patio de servicio y cajón de estacionamiento para un auto. Tipo: Vivienda (Departamento). Superficie de terreno: 56.88 m². Construcción: 46.17 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 67390.', 2, NULL, 56.88, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('67682', 'Casa en Las Canteras, Pedro Escobedo', 'Casa', 'Venta', 1329000.0, 'Las Canteras, Pedro Escobedo, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 84.95 m². Con Escritura. Posesión física: Si. Clave de control: 67682.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('67802', 'Casa en Lomas de Juriquilla, Querétaro', 'Casa', 'Venta', 5467000.0, 'Lomas de Juriquilla, Querétaro, Querétaro', 'Casa habitación que consta de PB sala, comedor, cocina, medio baño; PA recámaras y baños. Tipo: Vivienda (Casa). Superficie de terreno: 278.37 m². Construcción: 251.77 m². Con Escritura. Posesión física: Si. Clave de control: 67802.', NULL, NULL, 278.37, '{}', true, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('67860', 'Casa en Privada Juriquilla, Querétaro', 'Casa', 'Venta', 6049000.0, 'Privada Juriquilla, Querétaro, Querétaro', 'Casa habitación que consta de PB sala, comedor, medio baño, recámara con baño y cochera; PA 3 recámaras con baño. Tipo: Vivienda (Casa). Superficie de terreno: 449.33 m². Construcción: 346.84 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 67860.', 3, NULL, 449.33, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68000', 'Local comercial en Centro, San Juan Del Río', 'Local', 'Venta', 8074000.0, 'Centro, San Juan Del Río, Querétaro', 'Local comercial Tipo: Locales (Comercial). Superficie de terreno: 1165 m². Construcción: 269.81 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 68000.', NULL, NULL, 1165.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68016', 'Casa en Villas Campestre, Corregidora', 'Casa', 'Venta', 1485200.0, 'Villas Campestre, Corregidora, Querétaro', 'Casa habitación: PB sala comedor, medio baño, cocina, patio de servicio, espacio para 2 autos; PA 2 recámaras, baño completo; azotea libre. Tipo: Vivienda (Casa). Superficie de terreno: 105 m². Construcción: 107 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 68016.', 2, NULL, 105.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68452', 'Casa en San Mateo, Querétaro', 'Casa', 'Venta', 2367000.0, 'San Mateo, Querétaro, Querétaro', 'Casa habitación. Tipo: Vivienda (Casa). Superficie de terreno: 131.6 m². Construcción: 148.3 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 68452.', NULL, NULL, 131.6, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68453', 'Departamento en San Pedrito Peñuelas, Querétaro', 'Departamento', 'Venta', 1379000.0, 'San Pedrito Peñuelas, Querétaro, Querétaro', 'Departamento habitacional. Tipo: Vivienda (Departamento). Superficie de terreno: 95 m². Construcción: 113 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 68453.', NULL, NULL, 95.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68654', 'Casa en Fracc. Zibata, El Marqués', 'Casa', 'Venta', 4373000.0, 'Fracc. Zibata, El Marqués, Querétaro', 'Casa habitación. Tipo: Vivienda (Casa). Superficie de terreno: 169.61 m². Construcción: 212.28 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 68654.', NULL, NULL, 169.61, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68740', 'Casa en Fracc Puerta Real, Corregidora', 'Casa', 'Venta', 2831000.0, 'Fracc Puerta Real, Corregidora, Querétaro', 'Casa habitacion ubicada en circuito cerrado Tipo: Vivienda (Casa). Superficie de terreno: 187 m². Construcción: 152.54 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 68740.', NULL, NULL, 187.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68743', 'Casa en Fracc Campestre Huertas la Joya, Querétaro', 'Casa', 'Venta', 13982000.0, 'Fracc Campestre Huertas la Joya, Querétaro, Querétaro', 'Casa habitacion Tipo: Vivienda (Casa). Superficie de terreno: 1537 m². Construcción: 1029 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 68743.', NULL, NULL, 1537.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68875', 'Casa en Real de San Isidro, San Juan Del Río', 'Casa', 'Venta', 1180000.0, 'Real de San Isidro, San Juan Del Río, Querétaro', 'Casa habitación. Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 65.7 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 68875.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68930', 'Casa en Lomas del Mirador IV, Corregidora', 'Casa', 'Venta', 1722000.0, 'Lomas del Mirador IV, Corregidora, Querétaro', 'Casa habitación. Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 106.19 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 68930.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('69161', 'Casa en Milenio III, Querétaro', 'Casa', 'Venta', 4996000.0, 'Milenio III, Querétaro, Querétaro', 'Casa habitación. Tipo: Vivienda (Casa). Superficie de terreno: 186 m². Construcción: 319 m². Con Acta de Adjudicación. Posesión física: No. Clave de control: 69161.', NULL, NULL, 186.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com');
