-- ====================================================================
-- Cargar SOLO las 25 propiedades de Querétaro con posesión física
-- Grupo Inmobiliario Orquídeas — ejecutar en Supabase > SQL Editor
-- Reemplaza por completo el catálogo: al terminar quedan exactamente estas 25.
-- ====================================================================

ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS clave_control text;

-- Limpia el catálogo actual (esto arregla el 'solo veo una' en producción)
DELETE FROM public.properties;

INSERT INTO public.properties
  (clave_control, titulo, tipo, operacion, precio, ubicacion, descripcion, recamaras, banos, area, imagenes, destacada, activa, contacto_nombre, contacto_telefono, contacto_email)
VALUES
  ('67390', 'Departamento en Real de la Loma, Querétaro', 'Departamento', 'Venta', 729000.0, 'Real de la Loma, Querétaro, Querétaro', 'Departamento habitacional en nivel tres: cocina, estancia, dos recámaras, baño completo, patio de servicio y cajón de estacionamiento para un auto. Tipo: Vivienda (Departamento). Superficie de terreno: 56.88 m². Construcción: 46.17 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 67390.', 2, NULL, 56.88, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('17890', 'Terreno agostadero en Vizarron, Cadereyta de Montes', 'Terreno', 'Venta', 857300.0, 'Vizarron, Cadereyta de Montes, Querétaro', 'Predio rústico irregular de romerío a terreno montuoso Tipo: Terreno Rústico (Agostadero). Superficie de terreno: 30021.6 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 17890.', NULL, NULL, 30021.64, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63240', 'Casa en Ejido San Miguel Carrillo, Querétaro', 'Casa', 'Venta', 987000.0, 'Ejido San Miguel Carrillo, Querétaro, Querétaro', 'Casa habitación de un nivel: sala, comedor, cocina, patio de servicio, 2 recámaras, 1 baño completo y cajón de estacionamiento. Tipo: Vivienda (Casa). Superficie de terreno: 60.75 m². Construcción: 47.43 m². Con Escritura. Posesión física: Si. Clave de control: 63240.', 2, 1, 60.75, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('20197', 'Terreno habitacional en Texas, Querétaro', 'Terreno', 'Venta', 1128900.0, 'Texas, Querétaro, Querétaro', 'Lote de terreno urbano habitacional Tipo: Terreno Urbano (Habitacional). Superficie de terreno: 300 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 20197.', NULL, NULL, 300.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68875', 'Casa en Real de San Isidro, San Juan Del Río', 'Casa', 'Venta', 1180000.0, 'Real de San Isidro, San Juan Del Río, Querétaro', 'Casa habitación. Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 65.7 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 68875.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('67682', 'Casa en Las Canteras, Pedro Escobedo', 'Casa', 'Venta', 1329000.0, 'Las Canteras, Pedro Escobedo, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 84.95 m². Con Escritura. Posesión física: Si. Clave de control: 67682.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('60246', 'Casa en San Miguel 2a etapa, Querétaro', 'Casa', 'Venta', 1429000.0, 'San Miguel 2a etapa, Querétaro, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Construcción: 88.87 m². Con Escritura. Posesión física: Si. Clave de control: 60246.', NULL, NULL, 72.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66362', 'Casa en Los Sauces, Querétaro', 'Casa', 'Venta', 1452000.0, 'Los Sauces, Querétaro, Querétaro', 'Casa habitación con local comercial Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Construcción: 130.84 m². Con Escritura. Posesión física: Si. Clave de control: 66362.', NULL, NULL, 90.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66424', 'Casa en Hacienda del Bosque, Corregidora', 'Casa', 'Venta', 1463000.0, 'Hacienda del Bosque, Corregidora, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 97.33 m². Construcción: 79.75 m². Con Escritura. Posesión física: Si. Clave de control: 66424.', NULL, NULL, 97.33, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('59931', 'Casa en México, San Juan Del Río', 'Casa', 'Venta', 1570000.0, 'México, San Juan Del Río, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 200 m². Construcción: 122.93 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 59931.', NULL, NULL, 200.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('67008', 'Casa en Barrio de San Isidro, San Juan Del Río', 'Casa', 'Venta', 1946000.0, 'Barrio de San Isidro, San Juan Del Río, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 223 m². Construcción: 134.97 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 67008.', NULL, NULL, 223.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63684', 'Casa en Pueblito Colonial, Corregidora', 'Casa', 'Venta', 1950000.0, 'Pueblito Colonial, Corregidora, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 119 m². Construcción: 132.65 m². Con Escritura. Posesión física: Si. Clave de control: 63684.', NULL, NULL, 119.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('65038', 'Casa en Los Candiles, Corregidora', 'Casa', 'Venta', 2055000.0, 'Los Candiles, Corregidora, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 105 m². Construcción: 136.96 m². Con Escritura. Posesión física: Si. Clave de control: 65038.', NULL, NULL, 105.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('66716', 'Casa en La Guitarrilla, San Juan Del Río', 'Casa', 'Venta', 2074000.0, 'La Guitarrilla, San Juan Del Río, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 119 m². Construcción: 115.88 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 66716.', NULL, NULL, 119.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('60752', 'Casa en La Uca, Ezequiel Montes', 'Casa', 'Venta', 2329000.0, 'La Uca, Ezequiel Montes, Querétaro', 'Casa habitación de 2 niveles: estancia, comedor, cocina, baños y 3 recámaras. Tipo: Vivienda (Casa). Superficie de terreno: 287 m². Construcción: 222.2 m². Con Escritura. Posesión física: Si. Clave de control: 60752.', 3, NULL, 287.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('61984', 'Casa en Cerrada de Santa Anita, Corregidora', 'Casa', 'Venta', 2396000.0, 'Cerrada de Santa Anita, Corregidora, Querétaro', 'Casa habitación de dos niveles: PB medio baño, estancia, comedor, cocina, área de lavado, cuarto de servicio con baño; PA recámara con sala de estar, closet, baño y recámaras. Tipo: Vivienda (Casa). Superficie de terreno: 116.36 m². Construcción: 135.05 m². Con Escritura. Posesión física: Si. Clave de control: 61984.', NULL, NULL, 116.36, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('64262', 'Terreno agrícola en Ex hacienda de Jofre, Querétaro', 'Terreno', 'Venta', 2666900.0, 'Ex hacienda de Jofre, Querétaro, Querétaro', 'Terreno en breña Tipo: Terreno Rústico (Agrícola). Superficie de terreno: 1121 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 64262.', NULL, NULL, 1121.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('65435', 'Terreno campestre en Ex hacienda de Jofre, Querétaro', 'Terreno', 'Venta', 2747700.0, 'Ex hacienda de Jofre, Querétaro, Querétaro', 'Terreno en breña Tipo: Terreno Rústico (Campestre). Superficie de terreno: 1155 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 65435.', NULL, NULL, 1155.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68740', 'Casa en Fracc Puerta Real, Corregidora', 'Casa', 'Venta', 2831000.0, 'Fracc Puerta Real, Corregidora, Querétaro', 'Casa habitacion ubicada en circuito cerrado Tipo: Vivienda (Casa). Superficie de terreno: 187 m². Construcción: 152.54 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 68740.', NULL, NULL, 187.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('68654', 'Casa en Fracc. Zibata, El Marqués', 'Casa', 'Venta', 4373000.0, 'Fracc. Zibata, El Marqués, Querétaro', 'Casa habitación. Tipo: Vivienda (Casa). Superficie de terreno: 169.61 m². Construcción: 212.28 m². Con Acta de Adjudicación. Posesión física: Si. Clave de control: 68654.', NULL, NULL, 169.61, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('67802', 'Casa en Lomas de Juriquilla, Querétaro', 'Casa', 'Venta', 5467000.0, 'Lomas de Juriquilla, Querétaro, Querétaro', 'Casa habitación que consta de PB sala, comedor, cocina, medio baño; PA recámaras y baños. Tipo: Vivienda (Casa). Superficie de terreno: 278.37 m². Construcción: 251.77 m². Con Escritura. Posesión física: Si. Clave de control: 67802.', NULL, NULL, 278.37, '{}', true, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('63242', 'Casa en Bosques del Acueducto, Querétaro', 'Casa', 'Venta', 6957000.0, 'Bosques del Acueducto, Querétaro, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 232.1 m². Construcción: 362.36 m². Con Escritura. Posesión física: Si. Clave de control: 63242.', NULL, NULL, 232.1, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('64436', 'Casa en Fracc. Villas del Mesón, Querétaro', 'Casa', 'Venta', 11669000.0, 'Fracc. Villas del Mesón, Querétaro, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 1207 m². Construcción: 547.04 m². Con Escritura. Posesión física: Si. Clave de control: 64436.', NULL, NULL, 1207.0, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('65259', 'Casa en Residencial Balvanera, Corregidora', 'Casa', 'Venta', 11990000.0, 'Residencial Balvanera, Corregidora, Querétaro', 'Casa habitación en fraccionamiento privado Tipo: Vivienda (Casa). Superficie de terreno: 1137.19 m². Construcción: 668.71 m². Con Escritura. Posesión física: Si. Clave de control: 65259.', NULL, NULL, 1137.19, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('60474', 'Terreno habitacional en Desarrollo Centro Sur, Querétaro', 'Terreno', 'Venta', 44057000.0, 'Desarrollo Centro Sur, Querétaro, Querétaro', 'Terreno en breña urbano sin construcciones Tipo: Terreno Urbano (Habitacional). Superficie de terreno: 4230.1 m². Construcción: 0 m². Con Escritura. Posesión física: Si. Clave de control: 60474.', NULL, NULL, 4230.1, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com');
