-- 25 propiedades — Grupo Inmobiliario Orquídeas
-- Ejecutar en Supabase > SQL Editor. El slug se autogenera por trigger.
-- precio = 0 (PENDIENTE definir). operacion = 'Venta' por defecto.
INSERT INTO public.properties
  (titulo, tipo, operacion, precio, ubicacion, descripcion, recamaras, banos, area, imagenes, destacada, activa, contacto_nombre, contacto_telefono, contacto_email)
VALUES
  ('Terreno agostadero en Vizarron, Cadereyta de Montes', 'Terreno', 'Venta', 0, 'Vizarron, Cadereyta de Montes, Querétaro', 'Predio rústico irregular de romerío a terreno montuoso Tipo: Terreno Rústico (Agostadero). Superficie de terreno: 30021.64 m². Dirección: Predio el quemadito Poblado de Vizarron Km.75. Clave de control: 17890.', NULL, NULL, 30021.64, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Terreno habitacional en Texas, Querétaro', 'Terreno', 'Venta', 0, 'Texas, Querétaro, Querétaro', 'Lote de terreno urbano habitacional Tipo: Terreno Urbano (Habitacional). Superficie de terreno: 300 m². Dirección: Eduardo Luque Loya S/N, Lt 21, Mz 51. Clave de control: 20197.', NULL, NULL, 300, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en México, San Juan Del Río', 'Casa', 'Venta', 0, 'México, San Juan Del Río, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 200 m². Dirección: Michoacan Lote 38 mza 8 int 33. Clave de control: 59931.', NULL, NULL, 200, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en San Miguel 2a etapa, Querétaro', 'Casa', 'Venta', 0, 'San Miguel 2a etapa, Querétaro, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 72 m². Dirección: Av. San Samael, interior 70, cond. Privada Santa Julia, lote 10, mza 10 5273. Clave de control: 60246.', NULL, NULL, 72, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Terreno habitacional en Desarrollo Centro Sur, Querétaro', 'Terreno', 'Venta', 0, 'Desarrollo Centro Sur, Querétaro, Querétaro', 'Terreno en breña urbano sin construcciones Tipo: Terreno Urbano (Habitacional). Superficie de terreno: 4230.1 m². Dirección: Av. Paseo del Sur, Interior 4 9805. Clave de control: 60474.', NULL, NULL, 4230.1, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en La Uca, Ezequiel Montes', 'Casa', 'Venta', 0, 'La Uca, Ezequiel Montes, Querétaro', 'Casa habitación de 2 niveles: estancia, comedor, cocina, baños y 3 recámaras. Tipo: Vivienda (Casa). Superficie de terreno: 287 m². Dirección: Manuel Acuña 7. Clave de control: 60752.', 3, NULL, 287, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Cerrada de Santa Anita, Corregidora', 'Casa', 'Venta', 0, 'Cerrada de Santa Anita, Corregidora, Querétaro', 'Casa habitación de dos niveles. PB: medio baño, estancia, comedor, cocina, área de lavado, cuarto de servicio con baño. PA: recámara con sala de estar, closet y baño, pasillo de distribución y recámaras. Tipo: Vivienda (Casa). Superficie de terreno: 116.36 m². Dirección: Circuito Canarios 7-4, Lt 4. Clave de control: 61984.', NULL, NULL, 116.36, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Ejido San Miguel Carrillo, Querétaro', 'Casa', 'Venta', 0, 'Ejido San Miguel Carrillo, Querétaro, Querétaro', 'Casa habitación de un nivel: sala, comedor, cocina, patio de servicio, 2 recámaras, 1 baño completo y cajón de estacionamiento. Tipo: Vivienda (Casa). Superficie de terreno: 60.75 m². Dirección: Agustín González Medina, Condominio Eduardo Balvanera 4860 int 18. Clave de control: 63240.', 2, 1, 60.75, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Bosques del Acueducto, Querétaro', 'Casa', 'Venta', 0, 'Bosques del Acueducto, Querétaro, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 232.1 m². Dirección: Ibiza 7, Lt 30, Mza 3. Clave de control: 63242.', NULL, NULL, 232.1, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Pueblito Colonial, Corregidora', 'Casa', 'Venta', 0, 'Pueblito Colonial, Corregidora, Querétaro', 'Casa habitación, 2 niveles Tipo: Vivienda (Casa). Superficie de terreno: 119 m². Dirección: Saldiveña 13, Lt 271, Mza 12. Clave de control: 63684.', NULL, NULL, 119, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Terreno agrícola en Ex hacienda de Jofre, Querétaro', 'Terreno', 'Venta', 0, 'Ex hacienda de Jofre, Querétaro, Querétaro', 'Terreno en breña Tipo: Terreno Rústico (Agrícola). Superficie de terreno: 1121 m². Dirección: Carretera San Luis Potosi Queretaro, KM 35 S/N. Clave de control: 64262.', NULL, NULL, 1121, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Fracc. Villas del Mesón, Querétaro', 'Casa', 'Venta', 0, 'Fracc. Villas del Mesón, Querétaro, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 1207 m². Dirección: Hacienda Montenegro 113 G, Lts 44 y 45, Mza 7. Clave de control: 64436.', NULL, NULL, 1207, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Los Candiles, Corregidora', 'Casa', 'Venta', 0, 'Los Candiles, Corregidora, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 105 m². Dirección: Jose Maria Vertiz 461, Lt 48, Mza 43. Clave de control: 65038.', NULL, NULL, 105, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Residencial Balvanera, Corregidora', 'Casa', 'Venta', 0, 'Residencial Balvanera, Corregidora, Querétaro', 'Casa habitación en fraccionamiento privado Tipo: Vivienda (Casa). Superficie de terreno: 1137.19 m². Dirección: Cowdry Park Polo 21, Lt 10, Mza 8. Clave de control: 65259.', NULL, NULL, 1137.19, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Terreno campestre en Ex hacienda de Jofre, Querétaro', 'Terreno', 'Venta', 0, 'Ex hacienda de Jofre, Querétaro, Querétaro', 'Terreno en breña Tipo: Terreno Rústico (Campestre). Superficie de terreno: 1155 m². Dirección: Fraccion de terreno Eje Central de la Super Carretera Constitucion SN. Clave de control: 65435.', NULL, NULL, 1155, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Los Sauces, Querétaro', 'Casa', 'Venta', 0, 'Los Sauces, Querétaro, Querétaro', 'Casa habitación con local comercial Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Dirección: Granada 57. Clave de control: 66362.', NULL, NULL, 90, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Hacienda del Bosque, Corregidora', 'Casa', 'Venta', 0, 'Hacienda del Bosque, Corregidora, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 97.33 m². Dirección: Avenida Siglo XVI numero 4, Condominio 3 Rios 20, Mza 2, Lt 2. Clave de control: 66424.', NULL, NULL, 97.33, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en La Guitarrilla, San Juan Del Río', 'Casa', 'Venta', 0, 'La Guitarrilla, San Juan Del Río, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 119 m². Dirección: Thaiti, Condominio 4 28. Clave de control: 66716.', NULL, NULL, 119, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Barrio de San Isidro, San Juan Del Río', 'Casa', 'Venta', 0, 'Barrio de San Isidro, San Juan Del Río, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 223 m². Dirección: Hacienda de Coapa 70 Int 70, Cond V-D Hacienda Las Nueces, Lt 20. Clave de control: 67008.', NULL, NULL, 223, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Departamento en Real de la Loma, Querétaro', 'Departamento', 'Venta', 0, 'Real de la Loma, Querétaro, Querétaro', 'Departamento habitacional en nivel tres: cocina, estancia, dos recámaras, baño completo, patio de servicio y cajón de estacionamiento para un auto. Tipo: Vivienda (Departamento). Superficie de terreno: 56.88 m². Dirección: Monte Casero, Condominio Lomas Diamante (unidad condominal Loma Verde), Delegacion Felix Osores Sotomayor 561-B, Int 7-GB, Lt I, Mza 1. Clave de control: 67390.', 2, NULL, 56.88, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Las Canteras, Pedro Escobedo', 'Casa', 'Venta', 0, 'Las Canteras, Pedro Escobedo, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Dirección: Privada Cenefa 2, Lt 31, Mza 6. Clave de control: 67682.', NULL, NULL, 90, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Lomas de Juriquilla, Querétaro', 'Casa', 'Venta', 0, 'Lomas de Juriquilla, Querétaro, Querétaro', 'Casa habitación: PB sala, comedor, cocina, 1/2 baño; PA recámaras y baños. Tipo: Vivienda (Casa). Superficie de terreno: 278.37 m². Dirección: Cordillera de los Andes 2014, Lt 18, Mza 1. Clave de control: 67802.', NULL, 2, 278.37, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Fracc. Zibata, El Marqués', 'Casa', 'Venta', 0, 'Fracc. Zibata, El Marqués, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 169.61 m². Dirección: Tuna, Lote 5, Manzana 5 28 int 33. Clave de control: 68654.', NULL, NULL, 169.61, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Fracc Puerta Real, Corregidora', 'Casa', 'Venta', 0, 'Fracc Puerta Real, Corregidora, Querétaro', 'Casa habitación ubicada en circuito cerrado Tipo: Vivienda (Casa). Superficie de terreno: 187 m². Dirección: Circuito Puerta del Sol 5, Int 108, Cond Villa del Rio. Clave de control: 68740.', NULL, NULL, 187, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com'),
  ('Casa en Real de San Isidro, San Juan Del Río', 'Casa', 'Venta', 0, 'Real de San Isidro, San Juan Del Río, Querétaro', 'Casa habitación Tipo: Vivienda (Casa). Superficie de terreno: 90 m². Dirección: San Patricio, Prolongacion Alvaro Obregon, Barrio de San Isidro 35. Clave de control: 68875.', NULL, NULL, 90, '{}', false, true, 'Roberto Alcántara', '5583672523', 'robertoe.alcantara@gmail.com');
